spring.application.name=config-server

server.port=8888

spring.cloud.config.server.git.uri=file:///C:/Users/gtoc2/OneDrive/Documents/Digital-Nurture-Java-FSE/Week4_Microservices/config-repo

spring.cloud.config.server.git.default-label=main